### PR TITLE
feat: Add support for LEDVANCE SmartPlus Plug CH

### PR DESCRIPTION
**Pull request by storm1ng**
AC30904
Chip: WB2S (bk7231t)
Existing Profile: oem-bk7231s-dltj-1.3.5-sdk-1.0.2-40.00

Since I don't have the tools to dump the firmware, I created the device.json by combining the LEDVANCE SmartPlus EU Multi Socket Power Strip (which is using the same firmware) and the LEDVANCE SmartPlus Plug EU (which the same plug just with a different socket) and successfully cut the plug.

Flashing ESPHome Kickstart is working as well.

Link: https://www.ledvance.com/consumer/products/smart-home/smart-components/smart-wifi/smart-indoor-components-with-wifi-technology/smart-plugs-with-wifi-technology/plug-with-smart-socket-to-control-non-smart-devices-with-wifi-technology--pairable-with-remote-controller-c6482?productId=68029

### CODE REVIEW

**Comment by Cossid** [comment]
The problem with doing it this way is it is unclear which device the schema and device configuration belong to.  Can you please post the the contents of the `Source Data` available from Kickstart's + LTChipTool's UPK2ESPHome?

**Comment by storm1ng** [comment]
Is there an easy way to re-flash Kickstart onto a plug which already has custom ESPHome  on it?

**Comment by storm1ng** [comment]
Nevermind, I was able to reflash kickstart.

Please find the Source Data below:
[ledvance-smartplus-plug-ch-source-data.json](https://github.com/tuya-cloudcutter/tuya-cloudcutter.github.io/files/14401269/ledvance-smartplus-plug-ch-source-data.json)

**Comment by storm1ng** [comment]
Thanks for the correction and the merge.

**Comment by storm1ng** [comment]
@Cossid Something seems of. When I use the schema with your changes I am not able to get any sensor readings (voltage,wattage, current) at all. 
Might this be related to the fact that I already used my "stitched together" approach? Because with my tinkered schema I get those readings...

The plug with ESPHome is another plug than the one I cut but the same model of course.

In my source data there are two schemas, 000003375u (the one you used) and 000002zjt3 (the one which seems to have the same values as the EU plug). I don't know why we have two sections but it seems that with 000003375u I cannot get any proper reading at all.

**Comment by storm1ng** [comment]
Maybe it's just the tuya local or the local tuya integration which is off. However, those two sections are present with different values.

**Comment by Cossid** [comment]
Your storage area had 2 schemas, but that is because cloudcutter adds whatever schema belongs to the device of the profile used to cut.  In this case, `000002zjt3` belongs to the Arlec plug when you used by firmware version/name.  The other one, `000003375u` is the one Tuya installed on the device when you connected the device to SmartLife, and is unique to that device.  But the schemas do not matter at all if you are using ESPHome, only LocalTuya/TinyTuya.

https://upk.libretiny.eu/?profile=ledvance-smartplus-plug-ch is the ESPHome generated profile from the storage data of the device you posted.

**Comment by storm1ng** [comment]
Ah, thanks for the clarification. 😄

**Pull request merged**
