### PR TITLE
Crabtek BSD01 16A USA Plug

### PR DESCRIPTION
**Pull request by micahriley88**
Link: https://www.amazon.com/gp/product/B09TSZLT9V/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Dumped this one using UART method.

I took apart an assortment of Tuya devices, but somehow forgot pictures for this one.
The plug's disassembly and its internals closely resemble other plugs with this form factor.

### CODE REVIEW

**Comment by Cossid** [comment]
You list a model as `BSD01`, but the product page listed `CTE-P12` as well.  Is either one printed on the device itself?  Also, is there branding present on the product?  If not, we usually mark them as Tuya-Generic as the seller name isn't terribly relevant if multiple resellers sell the same thing.

**Comment by kuba2k2** [comment]
I have a similar one (but EU version) and it's called BSD34. AFAIK it's actually written on the enclosure.

**Comment by Cossid** [comment]
Leaving as Crabtek for now, but might change if others report a similar device under a different brand.

**Comment by micahriley88** [comment]
> Leaving as Crabtek for now, but might change if others report a similar device under a different brand.

image

It's branded as Crabtek with the provided model. 
I'm just realizing now that the ground prong is sort of blocking the name, but you can see the logo.

**Comment by Cossid** [comment]
Thanks for clarifying, then yes, We'll leave that as Crabtek mfg then.  Most plugs that look like that don't have branding on them.  I added the Amazon product code as well for anyone who may search by that.

**Pull request merged**
