### PR TITLE
New device - Tuya Generic Brazil 2-CH Wall Socket with USB

### PR DESCRIPTION
**Pull request by felipecrs**
First: thank you so much for working on this project. I was able to flash ESPHome in my device without needing any soldering thanks to this.

Since my experiment was successful, I wanted to give back somehow. Thus, this PR.

However, I have no idea whatsoever on what to add under `schemas` and `device_configuration`.

Device store page: https://aliexpress.com/item/1005001558167947.html

FWIIW I possess DPs information extracted by TinyTuya:

```json
{ 
    "dps": {
        "1": false,
        "2": false,
        "9": 0,
        "10": 0,
        "38": "memory"
    },
    "mapping": {
        "1": {
            "code": "switch_1",
            "type": "Boolean",
            "values": {}
        },
        "2": {
            "code": "switch_2",
            "type": "Boolean",
            "values": {}
        }
    }
}
```

I also have the `.deviceconfig`:

```json
{
    "uuid": "RGnbdl8iPdMX",
    "auth_key": "icQTzTuPqFzeRzZk",
    "local_key": "dCcaCbG5sugaX6Zc",
    "sec_key": "Jlmv2iHxNiXX8STM",
    "device_id": "1Cr9xYQqPskqCTv1CrUr",
    "chip_family": "BK7231T",
    "profile_name": "1.0.7 - BK7231T / oem_bk7231s_rnd_switch",
    "device_slug": "lsc-3004200-wifi-outdoor-dual-socket"
}
```

Finally, looks like cloudcutter used this device as base to flash mine:

- https://github.com/tuya-cloudcutter/tuya-cloudcutter.github.io/blob/master/devices/lsc-3004200-wifi-outdoor-dual-socket.json

And flash worked flawlessly.

I was able to figure out every meaningful pin number by using https://github.com/libretiny-eu/esphome-kickstart. Here is my ESPHome config (with pins) mimicking the default/factory behavior of the device:

```yaml
esphome:
  project:
    name: Tuya.KS-10WBU
    version: "0.1.0"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

switch:
  - platform: gpio
    name: "${switch_1_name}"
    id: relay_1
    pin: P24
    on_turn_on:
      - output.turn_on: led_1
    on_turn_off:
      - output.turn_off: led_1
    restore_mode: ${relay_restore_mode}
  - platform: gpio
    name: "${switch_2_name}"
    id: relay_2
    pin: P7
    on_turn_on:
      - output.turn_on: led_2
    on_turn_off:
      - output.turn_off: led_2
    restore_mode: ${relay_restore_mode}

output:
  - platform: gpio
    id: led_1
    pin: P11
    inverted: true
  - platform: gpio
    id: led_2
    pin: P8
    inverted: true

binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: P26
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay_1
      - timing:
          - ON for at least 4s
        then:
          - button.press: reset
  - platform: gpio
    id: button_2
    pin:
      number: P6
      mode: INPUT_PULLUP
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay_2
      - timing:
          - ON for at least 4s
        then:
          - button.press: reset

light:
  - platform: status_led
    id: blue_led
    pin:
      number: P10
      inverted: true
```

I would really appreciate any feedback.

### CODE REVIEW

**Comment by Cossid** [comment]
We require at minimum a schema in order for the profile to be useful for being cut.

Sometimes schema can be recovered from storage if the device was activated on SmartLife before cutting, sometimes it requires the secrets that CloudCutter removes.  If you temporarily put Kickstart on the device and use LTChipTool to get the "Source Data" storage.json from the UPK2ESPHome plugin tab, we might be able to get this information.  It would also cover the `device_configuration` section as well.  There will hopefully be 2 schemas, one belonging to this device, and a second that CloudCutter installed.

If you can post that storage data here, I can possibly amend and complete this PR.

**Comment by felipecrs** [comment]
Maybe we should write a guide on how people can extract all these data and put it upfront in the [`INSTRUCTIONS.md`](https://github.com/tuya-cloudcutter/tuya-cloudcutter/blob/main/INSTRUCTIONS.md), so that they get a chance to read it before flashing the device (and potentially losing information or making it more difficult to extract).

**Comment by Cossid** [comment]
Cutting is part of the process of flashing 3rd party firmware, it's just taking it a step further.

By storage, I mean the only data in the `Source Data` tab, it's the only thing there.  The storage area is untouched (but slightly altered) during the cutting/flashing process.  That's the same reason LTChipTool with kickstart can generate a profile.

Kickstart just has specific components pre-installed that LTChipTool utilizes within the UPK2ESPHome plugin, it's built into the firmware.

Writing profiles from cut devices isn't something we generally recommend because there is no guarantee all the data is available.  We'll do it when we can, but not enough people will do this to bother writing full documentation.

**Comment by felipecrs** [comment]
Alright. Let me flash Kickstart again and see what I can do from there.

**Comment by felipecrs** [comment]
There we go:

```json
{
    "gw_bi": {
        "uuid": "RGnbdl8iPdMX",
        "psk_key": null,
        "auth_key": "icQTzTuPqFzeRzZk",
        "ap_ssid": "A",
        "ap_passwd": null,
        "country_code": null,
        "prod_test": false
    },
    "user_param_key": {
        "bt1_lv": 0,
        "bt1_pin": 6,
        "bt2_lv": 0,
        "bt2_pin": 26,
        "bt_type": 0,
        "ch_cddpid1": 9,
        "ch_cddpid2": 10,
        "ch_dpid1": 1,
        "ch_dpid2": 2,
        "ch_flag1": 1,
        "ch_flag2": 1,
        "ch_num": 2,
        "crc": 77,
        "cyc_dpid": 42,
        "inch_dp": 44,
        "init_conf": 38,
        "jv": "1.0.4",
        "led1_lv": 0,
        "led1_pin": 8,
        "led2_lv": 0,
        "led2_pin": 11,
        "led_dp": 40,
        "lock_dp": 41,
        "module": "WB2S",
        "mxcl_led_m": 0,
        "net_trig": 2,
        "netled_lv": 0,
        "netled_pin": 10,
        "netn_led": 0,
        "nety_led": 1,
        "rand_dpid": 43,
        "reset_t": 3,
        "reuse_led_m": 0,
        "rl1_lv": 1,
        "rl1_pin": 7,
        "rl2_lv": 1,
        "rl2_pin": 24,
        "total_stat": 2
    },
    "gw_wsm": {
        "nc_tp": 4,
        "ssid": "Y2xvdWRjdXR0ZXJmbGFzaA==",
        "passwd": "YWJjZGFiY2Q=",
        "md": 0,
        "random": 0,
        "wfb64": 1,
        "stat": 2,
        "token": "AAAAAA",
        "region": "AA",
        "reg_key": null
    },
    "tls_ca_cnt": 0,
    "gw_di": {
        "abi": 0,
        "id": "1Cr9xYQqPskqCTv1CrUr",
        "swv": "1.0.7",
        "bv": "30.06",
        "pv": "2.2",
        "lpv": "3.3",
        "pk": "keya4gvchmtapm8n",
        "firmk": "keya4gvchmtapm8n",
        "cadv": "1.0.2",
        "cdv": "1.0.0",
        "dev_swv": "1.0.7",
        "s_id": "000001zi1l",
        "dtp": 0,
        "sync": 0,
        "attr_num": 0,
        "mst_tp_0": 0,
        "mst_ver_0": null,
        "mst_tp_1": 0,
        "mst_ver_1": null,
        "mst_tp_2": 0,
        "mst_ver_2": null,
        "mst_tp_3": 0,
        "mst_ver_3": null,
        "dminfo_name": null,
        "dminfo_code": null
    },
    "gw_ai": {
        "key": "Jlmv2iHxNiXX8STM",
        "lckey": "dCcaCbG5sugaX6Zc",
        "h_url": "http://10.42.42.1/d.json",
        "hs_url": null,
        "hs_psk": "https://a3.tuyaus.com/d.json",
        "mqs_url": null,
        "mq_url": "10.42.42.1:1883",
        "ai_sp": null,
        "mq_psk": "m2.tuyaus.com:8886",
        "time_z": "+01:00",
        "s_time_z": "[[1648342800,1667091600],[1679792400,1698541200]]",
        "wx_app_id": null,
        "wx_uuid": null,
        "dy_tls_m": 1
    },
    "timer_arr": {
        "lastFetchTime": 0,
        "cnt": 0
    },
    "save_off_stat": {
        "power": [
            false,
            false
        ]
    },
    "000001zi1l": [
        {
            "mode": "rw",
            "property": {
                "type": "bool"
            },
            "id": 1,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "type": "bool"
            },
            "id": 2,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "min": 0,
                "max": 86400,
                "scale": 0,
                "step": 1,
                "type": "value"
            },
            "id": 9,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "min": 0,
                "max": 86400,
                "scale": 0,
                "step": 1,
                "type": "value"
            },
            "id": 10,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "range": [
                    "off",
                    "on",
                    "memory"
                ],
                "type": "enum"
            },
            "id": 38,
            "type": "obj"
        }
    ],
    "000001xrl8": [
        {
            "mode": "rw",
            "property": {
                "type": "bool"
            },
            "id": 1,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "type": "bool"
            },
            "id": 2,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "min": 0,
                "max": 86400,
                "scale": 0,
                "step": 1,
                "type": "value"
            },
            "id": 9,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "min": 0,
                "max": 86400,
                "scale": 0,
                "step": 1,
                "type": "value"
            },
            "id": 10,
            "type": "obj"
        },
        {
            "mode": "rw",
            "property": {
                "range": [
                    "off",
                    "on",
                    "memory"
                ],
                "type": "enum"
            },
            "id": 38,
            "type": "obj"
        }
    ],
    "em_sys_env": "BK7231S_2M",
    "mf_test_close": true
}
```

Tuya API output from _Schema download_ tab:

```json
{
    "tokenResponse": {
        "expire_time": 300,
        "region": "EU",
        "secret": "3BLU",
        "token": "gaKz29sF"
    },
    "deviceApi": "http://a.tuyaeu.com/d.json",
    "activeRequest": {
        "token": "gaKz29sF",
        "productKey": "keya4gvchmtapm8n",
        "softVer": "1.1.2",
        "protocolVer": "2.2",
        "baselineVer": "40.00",
        "cadVer": "1.0.3",
        "cdVer": "1.0.0",
        "options": "{\"isFK\":true}",
        "t": 1701185407
    },
    "activeResponse": {
        "schema": [
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "type": "bool"
                },
                "id": 1
            },
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1,
                    "type": "value"
                },
                "id": 9
            },
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "range": [
                        "off",
                        "on",
                        "memory"
                    ],
                    "type": "enum"
                },
                "id": 38
            },
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "range": [
                        "relay",
                        "pos",
                        "none"
                    ],
                    "type": "enum"
                },
                "id": 40
            },
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "type": "bool"
                },
                "id": 41
            },
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "type": "string",
                    "maxlen": 255
                },
                "id": 42
            },
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "type": "string",
                    "maxlen": 255
                },
                "id": 43
            },
            {
                "type": "obj",
                "mode": "rw",
                "property": {
                    "type": "string",
                    "maxlen": 255
                },
                "id": 44
            }
        ],
        "devId": "bf91d54ec16480a925fqrc",
        "resetFactory": false,
        "timeZone": "+01:00",
        "capability": 1025,
        "secKey": "g>VCRp++Y9_kV|jR",
        "stdTimeZone": "+01:00",
        "schemaId": "0000034xxs",
        "dstIntervals": [
            [
                1711846800,
                1729990800
            ],
            [
                1743296400,
                1761440400
            ],
            [
                1774746000,
                1792890000
            ],
            [
                1806195600,
                1824944400
            ],
            [
                1837645200,
                1856394000
            ]
        ],
        "localKey": "~k#6)qSnx6JN[cu2"
    },
    "checkResponse": {
        "error_devices": [],
        "success_devices": [
            {
                "id": "bf91d54ec16480a925fqrc",
                "ip": "2a06:98c0:3600::103",
                "lat": "",
                "lon": "",
                "name": "IoT Switch M04",
                "online": false,
                "product_id": "7o0gim7xrxdy7hma",
                "uuid": "5e98356d36f3b1be"
            }
        ]
    },
    "modelResponse": {
        "model": {
            "modelId": "0000034xxs",
            "services": [
                {
                    "actions": [],
                    "code": "",
                    "description": "",
                    "events": [],
                    "name": "\u9ed8\u8ba4\u670d\u52a1",
                    "properties": [
                        {
                            "abilityId": 1,
                            "accessMode": "rw",
                            "code": "switch_1",
                            "description": "",
                            "extensions": {
                                "iconName": "icon-dp_power2",
                                "attribute": "149"
                            },
                            "name": "\u5f00\u51731",
                            "typeSpec": {
                                "type": "bool",
                                "typeDefaultValue": false
                            }
                        },
                        {
                            "abilityId": 9,
                            "accessMode": "rw",
                            "code": "countdown_1",
                            "description": "",
                            "extensions": {
                                "iconName": "icon-dp_time2",
                                "attribute": "132"
                            },
                            "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
                            "typeSpec": {
                                "max": 86400,
                                "min": 0,
                                "scale": 0,
                                "step": 1,
                                "type": "value",
                                "typeDefaultValue": 0,
                                "unit": "s"
                            }
                        },
                        {
                            "abilityId": 38,
                            "accessMode": "rw",
                            "code": "relay_status",
                            "description": "",
                            "extensions": {
                                "iconName": "icon-zhuangtai",
                                "attribute": "644"
                            },
                            "name": "\u4e0a\u7535\u72b6\u6001\u8bbe\u7f6e",
                            "typeSpec": {
                                "range": [
                                    "off",
                                    "on",
                                    "memory"
                                ],
                                "type": "enum",
                                "typeDefaultValue": "off"
                            }
                        },
                        {
                            "abilityId": 40,
                            "accessMode": "rw",
                            "code": "light_mode",
                            "description": "",
                            "extensions": {
                                "iconName": "tcl_function_light",
                                "attribute": "132"
                            },
                            "name": "\u6307\u793a\u706f\u6a21\u5f0f",
                            "typeSpec": {
                                "range": [
                                    "relay",
                                    "pos",
                                    "none"
                                ],
                                "type": "enum",
                                "typeDefaultValue": "relay"
                            }
                        },
                        {
                            "abilityId": 41,
                            "accessMode": "rw",
                            "code": "child_lock",
                            "description": "",
                            "extensions": {
                                "iconName": "icon-dp_power2",
                                "attribute": "128"
                            },
                            "name": "\u7ae5\u9501",
                            "typeSpec": {
                                "type": "bool",
                                "typeDefaultValue": false
                            }
                        },
                        {
                            "abilityId": 42,
                            "accessMode": "rw",
                            "code": "cycle_time",
                            "description": "",
                            "extensions": {
                                "iconName": "icon-dp_time3",
                                "attribute": "128"
                            },
                            "name": "\u5faa\u73af\u5b9a\u65f6",
                            "typeSpec": {
                                "maxlen": 255,
                                "type": "string",
                                "typeDefaultValue": ""
                            }
                        },
                        {
                            "abilityId": 43,
                            "accessMode": "rw",
                            "code": "random_time",
                            "description": "",
                            "extensions": {
                                "iconName": "icon-dp_time2",
                                "attribute": "128"
                            },
                            "name": "\u968f\u673a\u5b9a\u65f6",
                            "typeSpec": {
                                "maxlen": 255,
                                "type": "string",
                                "typeDefaultValue": ""
                            }
                        },
                        {
                            "abilityId": 44,
                            "accessMode": "rw",
                            "code": "switch_inching",
                            "description": "",
                            "extensions": {
                                "iconName": "icon-dp_power2",
                                "attribute": "128"
                            },
                            "name": "\u70b9\u52a8\u5f00\u5173",
                            "typeSpec": {
                                "maxlen": 255,
                                "type": "string",
                                "typeDefaultValue": ""
                            }
                        }
                    ]
                }
            ]
        }
    },
    "errors": [],
    "detailsResponse": {
        "active_time": 1701185407,
        "asset_id": "165374831",
        "category": "tdq",
        "category_name": "Breaker",
        "icon": "smart/icon/ay1541662398752zwSuU/93b343160f0435ac8734a785b00019e9.jpg",
        "id": "bf91d54ec16480a925fqrc",
        "ip": "2a06:98c0:3600::103",
        "lat": "",
        "local_key": "~k#6)qSnx6JN[cu2",
        "lon": "",
        "model": "IoT Switch M04",
        "name": "IoT Switch M04",
        "online": false,
        "owner_id": "165374831",
        "product_id": "7o0gim7xrxdy7hma",
        "product_name": "IoT Switch M04",
        "sub": false,
        "time_zone": "+01:00",
        "uuid": "5e98356d36f3b1be"
    },
    "updateResponse": [
        {
            "channel": 0,
            "control_type": 0,
            "current_version": "1.1.2",
            "dev_type": 0,
            "last_upgrade_time": 0,
            "timeout": 0,
            "type": 0,
            "type_desc": "Main Module",
            "upgrade_status": 0
        }
    ],
    "deleteResponse": true,
    "cachedAt": 1701185408933,
    "cacheKey": "keya4gvchmtapm8n"
}
```

**Comment by felipecrs** [comment]
The image.jpg in such schema doesn't match my device at all:

93b343160f0435ac8734a785b00019e9

Although the generated ESPHome.yaml is perfect, it matches all the pins I had discovered and mimics the original device function very well.

**Comment by felipecrs** [comment]
This is how I fetched the schema:

image

Note I did not fill anything, I just pressed _Download_ with the pre-filled data.

**Comment by Cossid** [comment]
Yeah, this is a shared firmware, and LTChipTool caches the first schema it finds unless you supply very specific information cut profiles no longer have (and the functionality is currently broken anyway for pulling new non-cached ones).

Everything needed was present, this will be merged shortly.

**Pull request merged**
